args_all <- commandArgs(FALSE)
script_arg <- grep("^--file=", args_all, value = TRUE)
if (!length(script_arg)) stop("Run this script with Rscript.")
project_root <- dirname(dirname(normalizePath(sub("^--file=", "", script_arg[1]))))
.libPaths(c(file.path(project_root, ".R-library"), .libPaths()))
options(repos = c(CRAN = "https://cloud.r-project.org"))
app_dir <- file.path(project_root, "shinyApp")
report_dir <- file.path(project_root, "reports")
dir.create(report_dir, showWarnings = FALSE)
